## Data Wrangling

**Definition:**  
Data wrangling is the process of cleaning, transforming, and organizing raw data into a structured and usable format for analysis or modeling.

Raw data is almost never ready to use—columns might be mislabeled, values missing, formats inconsistent, etc. Wrangling is the work you do to fix all that so your analysis doesn’t give misleading results.

## Steps in Data Wrangling

1. Data collection / loading  
2. Data inspection (exploration)  
3. Handling missing data  
4. Data cleaning  
5. Data transformation  
6. Data integration (if needed)  
7. Data filtering and structuring  
8. Data validation / final check

In [1]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\ASUS TUF\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\ASUS TUF\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ASUS TUF\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\ASUS TUF\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\ASUS TUF\AppData\Local\Programs\Python\Python311\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [1]:
import pandas as pd

# Import the file and make a dataframe
reward_df = pd.read_csv('RewardsData.csv')

# View first 10 records
reward_df.head(10)

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,Tags
0,1,1/31/1992,Minneapolis,Georgia,55401,300,300,0,9/4/2020 0:15,12/16/2021 17:42,ClassOf2025
1,2,NaN,Los Angeles,Colorado,90210,320,320,0,8/19/2020 11:15,4/13/2022 14:28,ClassOf2025|apple
2,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,4/21/2021 10:54,Freshman|Developer
3,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,6/30/2022 22:22,GraduateStudent|admin|MBBvsDuke
4,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,12/30/2020 10:57,Student|NOBSBvsNDGame3|NOBSBvsNDGame3A
5,6,10/9/1995,G,AL,85588,7085,7395,310,8/18/2020 14:28,6/8/2022 23:55,GraduateStudent|admin
6,7,9/22/1995,NaN,NaN,NaN,570,570,0,8/21/2020 10:23,4/27/2022 16:27,ClassOf2025
7,8,NaN,NaN,NaN,NaN,2410,2410,0,8/22/2020 13:53,3/31/2022 1:56,ClassOf2022|21DZ
8,9,NaN,NaN,NaN,NaN,2895,3195,300,8/22/2020 14:03,10/10/2021 16:05,Student|Senior|DriveInNCSU|ClassificationPts|1...
9,10,7/20/1999,Winston Salem,NC,27106,8465,8515,50,8/22/2020 14:42,4/9/2022 14:10,GraduateStudent

`isna()` in pandas is used to detect missing values in a dataset; it returns a boolean structure (DataFrame or Series) of the same shape where `True` indicates a missing (NaN) value and `False` indicates a non-missing value.

In [2]:
reward_df.isna()

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,Tags
0,False,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
7247,False,True,True,True,True,False,False,False,False,False,False
7248,False,True,True,True,True,False,False,False,False,False,False
7249,False,False,True,True,True,False,False,False,False,False,False
7250,False,True,True,True,True,False,False,False,False,False,False
7251,False,True,True,True,True,False,False,False,False,False,False

In [3]:
# Since, True = 1 and False = 0, we can use sum() to get the count of total number of missing values.
missing_val_count = reward_df.isna().sum()
missing_val_count

User ID                   0
Birthdate              6080
City                   6922
State                  6922
Zip                    6922
Available Points          0
Total Points Earned       0
Points Spent              0
Joined On                 0
Last Seen               221
Tags                      0
dtype: int64

In [5]:
# Missing value shown in percentages
missing_val_percentage = missing_val_count / len(reward_df) * 100
missing_val_percentage

User ID                 0.000000
Birthdate              83.838941
City                   95.449531
State                  95.449531
Zip                    95.449531
Available Points        0.000000
Total Points Earned     0.000000
Points Spent            0.000000
Joined On               0.000000
Last Seen               3.047435
Tags                    0.000000
dtype: float64

In [6]:
# Here we can see that birthdate, city, and state have highest percentage of missing values. 
# But the last seen column have less percentage of missing values, so we can fill this column by using default values for further analysis.
reward_df['Last Seen']

0       12/16/2021 17:42
1        4/13/2022 14:28
2        4/21/2021 10:54
3        6/30/2022 22:22
4       12/30/2020 10:57
              ...
7247     6/30/2022 12:04
7248     6/28/2022 22:43
7249     6/30/2022 12:48
7250     6/30/2022 20:39
7251       7/1/2022 2:42
Name: Last Seen, Length: 7252, dtype: str

In [7]:
# We see that Last Seen column conatins the date time as string
# so we can convert this column into datetime format form the string type
reward_df['Last Seen'] = pd.to_datetime(reward_df['Last Seen'])
reward_df['Last Seen']

0      2021-12-16 17:42:00
1      2022-04-13 14:28:00
2      2021-04-21 10:54:00
3      2022-06-30 22:22:00
4      2020-12-30 10:57:00
               ...
7247   2022-06-30 12:04:00
7248   2022-06-28 22:43:00
7249   2022-06-30 12:48:00
7250   2022-06-30 20:39:00
7251   2022-07-01 02:42:00
Name: Last Seen, Length: 7252, dtype: datetime64[us]

In [8]:
reward_df['Last Seen'].max()

Timestamp('2022-07-01 08:36:00')

In [9]:
reward_df['Last Seen'].min()

Timestamp('2020-10-12 14:38:00')

`fillna()` in pandas is used to replace missing (NaN) values in a dataset with a specified value or method (such as mean, median, or forward/backward fill).

In [10]:
reward_df['Last Seen'].fillna(value=reward_df['Last Seen'].min())

0      2021-12-16 17:42:00
1      2022-04-13 14:28:00
2      2021-04-21 10:54:00
3      2022-06-30 22:22:00
4      2020-12-30 10:57:00
               ...
7247   2022-06-30 12:04:00
7248   2022-06-28 22:43:00
7249   2022-06-30 12:48:00
7250   2022-06-30 20:39:00
7251   2022-07-01 02:42:00
Name: Last Seen, Length: 7252, dtype: datetime64[us]

In [11]:
missing_val_count = reward_df.isna().sum()
missing_val_count

User ID                   0
Birthdate              6080
City                   6922
State                  6922
Zip                    6922
Available Points          0
Total Points Earned       0
Points Spent              0
Joined On                 0
Last Seen               221
Tags                      0
dtype: int64

In [12]:
reward_df_dropped = reward_df.dropna()
reward_df_dropped

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,Tags
0,1,1/31/1992,Minneapolis,Georgia,55401,300,300,0,9/4/2020 0:15,2021-12-16 17:42:00,ClassOf2025
2,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,2021-04-21 10:54:00,Freshman|Developer
3,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,2022-06-30 22:22:00,GraduateStudent|admin|MBBvsDuke
4,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,2020-12-30 10:57:00,Student|NOBSBvsNDGame3|NOBSBvsNDGame3A
5,6,10/9/1995,G,AL,85588,7085,7395,310,8/18/2020 14:28,2022-06-08 23:55:00,GraduateStudent|admin
...,...,...,...,...,...,...,...,...,...,...,...
7228,7219,6/12/2004,Lutherville,Maryland,21093,490,490,0,6/22/2022 17:28,2022-06-30 08:43:00,Student|ClassOf2026
7229,7220,8/7/1999,Winston-Salem,North Carolina,27106,430,430,0,6/22/2022 17:36,2022-06-26 16:39:00,Student|ClassOf2023
7236,7227,3/14/2000,Clemmons,North Carolina,27012,460,460,0,6/23/2022 22:18,2022-06-29 23:40:00,Student|GraduateStudent
7239,7230,5/18/1999,Winston Salem,North Carolina,27107,410,410,0,6/24/2022 16:03,2022-06-24 16:06:00,Student|GraduateStudent
7244,7235,6/20/2004,Guaynabo,Puerto Rico,969,440,440,0,6/27/2022 10:21,2022-07-01 08:36:00,Student|ClassOf2026

In [13]:
missing_val_count = reward_df_dropped.isna().sum()
missing_val_count

User ID                0
Birthdate              0
City                   0
State                  0
Zip                    0
Available Points       0
Total Points Earned    0
Points Spent           0
Joined On              0
Last Seen              0
Tags                   0
dtype: int64

In [14]:
# Drop the tags column from the new dataframe
reward_df_dropped = reward_df_dropped.drop(columns='Tags')
reward_df_dropped

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen
0,1,1/31/1992,Minneapolis,Georgia,55401,300,300,0,9/4/2020 0:15,2021-12-16 17:42:00
2,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,2021-04-21 10:54:00
3,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,2022-06-30 22:22:00
4,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,2020-12-30 10:57:00
5,6,10/9/1995,G,AL,85588,7085,7395,310,8/18/2020 14:28,2022-06-08 23:55:00
...,...,...,...,...,...,...,...,...,...,...
7228,7219,6/12/2004,Lutherville,Maryland,21093,490,490,0,6/22/2022 17:28,2022-06-30 08:43:00
7229,7220,8/7/1999,Winston-Salem,North Carolina,27106,430,430,0,6/22/2022 17:36,2022-06-26 16:39:00
7236,7227,3/14/2000,Clemmons,North Carolina,27012,460,460,0,6/23/2022 22:18,2022-06-29 23:40:00
7239,7230,5/18/1999,Winston Salem,North Carolina,27107,410,410,0,6/24/2022 16:03,2022-06-24 16:06:00
7244,7235,6/20/2004,Guaynabo,Puerto Rico,969,440,440,0,6/27/2022 10:21,2022-07-01 08:36:00

In [15]:
# Get list of unique values from city column
city_unique_values = reward_df_dropped["City"].unique().tolist()

# sort the values
# city_unique_values.()
city_unique_values.sort()
city_unique_values

['Atlanta',
 'Aurora ',
 'Austin',
 'Bakersfield',
 'Belmont ',
 'Bethesda ',
 'Bourne',
 'Chapel Hill',
 'Charlotte',
 'Charlotte ',
 'Clemmons',
 'Cleveland',
 'Clovis',
 'Dallas',
 'Delhi',
 'Delran',
 'Downers Grove',
 'Durham',
 'Duxbury',
 'Edina',
 'Fort Myers ',
 'G',
 'Gainesville',
 'Greensboro',
 'Guaynabo',
 'Huntersville',
 'Indian Trail',
 'Jacksonville ',
 'Jamesville',
 'Larchmont',
 'Libertyville',
 'Lincoln University',
 'Littleton',
 'Lmao',
 'Locust',
 'Louisville',
 'Lutherville',
 'Malvern',
 'Manhattan beach ',
 'Marblehead',
 'Memphis',
 'Merida',
 'Milwaukee',
 'Minneapolis ',
 'Mooresville',
 'Morganton',
 'Mt. Pleasant ',
 'Nashville',
 'Northport',
 'Oakwood',
 'Orleans ',
 'Ormond Beach',
 'Palm Beach Gardens',
 'Palmetto Bay',
 'Perry',
 'Pittsburgh',
 'Rex',
 'Rocky hill',
 'Rome',
 'San Marcos',
 'Sharon',
 'Smithtown',
 'Summit',
 'Supply',
 'Terrace Park',
 'Thomasville',
 'Valrico ',
 'Walkertown',
 'Waukegan',
 'Waxhaw',
 'West Chester',
 'Weston',
 'Westport',
 'Whitesboro',
 'Winston Salem',
 'Winston Salem ',
 'Winston salem',
 'Winston salem ',
 'Winston-Salem',
 'Winston-Salem ',
 'Winston-Salem, NC',
 'Winston-salem',
 'Wyckoff',
 'dover',
 'winston salem ']

In [16]:
# We observe that there are variations for Winston Salem, we can replace all of them using replace()
reward_df_dropped['City'].replace(to_replace=['Winston Salem',  'Winston Salem ',  'Winston salem',  'Winston salem ', 'Winston-Salem', 'Winston-Salem ',
     'Winston-Salem, NC', 'Winston-salem'],value = "Winston-Salem")

0        Minneapolis
2              Merida
3       Winston-Salem
4       Winston-Salem
5                   G
            ...
7228      Lutherville
7229    Winston-Salem
7236         Clemmons
7239    Winston-Salem
7244         Guaynabo
Name: City, Length: 172, dtype: str

In [17]:
# Remove all the trailing and leading white spaces
reward_df_dropped['City'].str.strip()

0         Minneapolis
2              Merida
3       Winston-Salem
4       Winston-Salem
5                   G
            ...
7228      Lutherville
7229    Winston-Salem
7236         Clemmons
7239    Winston Salem
7244         Guaynabo
Name: City, Length: 172, dtype: str

In [18]:
# Fix any casing issues 
reward_df_dropped['City'].str.title()

0        Minneapolis
2              Merida
3       Winston-Salem
4       Winston-Salem
5                   G
            ...
7228      Lutherville
7229    Winston-Salem
7236         Clemmons
7239    Winston Salem
7244         Guaynabo
Name: City, Length: 172, dtype: str

In [19]:
# Get list of unique values from state column
state_unique_values = reward_df_dropped["State"].unique()

# sort the values
state_unique_values = sorted(state_unique_values)
state_unique_values

['AL',
 'CT',
 'California',
 'Colorado',
 'Connecticut',
 'District of Columbia',
 'FL',
 'Florida',
 'GA',
 'Georgia',
 'Illinois',
 'Kentucky',
 'MA',
 'MD',
 'MN',
 'Maryland',
 'Massachusetts',
 'NC',
 'NJ',
 'NY',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'OH',
 'Ohio',
 'PA',
 'Pennsylvania',
 'Puerto Rico',
 'SC',
 'TN',
 'TX',
 'Tennessee',
 'Texas',
 'WI']

In [21]:
# The state column contains both states full form and abbrebiation, so we convert them to same notation
us_state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "Virgin Islands, U.S.": "VI",
}

In [22]:
# Replace each state with abbrebiation
for state_name in us_state_to_abbrev:
    reward_df_dropped['State'] = reward_df_dropped['State'].replace(
        state_name,
        us_state_to_abbrev[state_name]
    )

In [23]:
# Pandas can do this directly using dictionary mapping
reward_df_dropped['State'] = reward_df_dropped['State'].replace(us_state_to_abbrev)

In [24]:
# Get list of unique values from state column
state_unique_values = reward_df_dropped["State"].unique()

# sort the values
state_unique_values = sorted(state_unique_values)
state_unique_values

['AL',
 'CA',
 'CO',
 'CT',
 'DC',
 'FL',
 'GA',
 'IL',
 'KY',
 'MA',
 'MD',
 'MN',
 'NC',
 'NJ',
 'NM',
 'NY',
 'OH',
 'PA',
 'PR',
 'SC',
 'TN',
 'TX',
 'WI']

In [25]:
# Convert the us_state_to_abbrev dictionary to df for merginin with reward df
states_df =pd.DataFrame(list(us_state_to_abbrev.items()), columns=['State Name', 'State']) 
# State column matches with the olumn of reward df while merginig
states_df.head(5)

   State Name State
0     Alabama    AL
1      Alaska    AK
2     Arizona    AZ
3    Arkansas    AR
4  California    CA

In [26]:
# Merging
reward_df_dropped = pd.merge(reward_df_dropped, states_df, on="State", how="left")
reward_df_dropped

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,State Name
0,1,1/31/1992,Minneapolis,GA,55401,300,300,0,9/4/2020 0:15,2021-12-16 17:42:00,Georgia
1,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,2021-04-21 10:54:00,Alabama
2,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,2022-06-30 22:22:00,North Carolina
3,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,2020-12-30 10:57:00,North Carolina
4,6,10/9/1995,G,AL,85588,7085,7395,310,8/18/2020 14:28,2022-06-08 23:55:00,Alabama
...,...,...,...,...,...,...,...,...,...,...,...
167,7219,6/12/2004,Lutherville,MD,21093,490,490,0,6/22/2022 17:28,2022-06-30 08:43:00,Maryland
168,7220,8/7/1999,Winston-Salem,NC,27106,430,430,0,6/22/2022 17:36,2022-06-26 16:39:00,North Carolina
169,7227,3/14/2000,Clemmons,NC,27012,460,460,0,6/23/2022 22:18,2022-06-29 23:40:00,North Carolina
170,7230,5/18/1999,Winston Salem,NC,27107,410,410,0,6/24/2022 16:03,2022-06-24 16:06:00,North Carolina
171,7235,6/20/2004,Guaynabo,PR,969,440,440,0,6/27/2022 10:21,2022-07-01 08:36:00,Puerto Rico

In [27]:
# Rename State column into State Abbrebiation
reward_df_dropped =  reward_df_dropped.rename(columns={"State":"State Abbrebiation"})
reward_df_dropped.head(5)

,User ID,Birthdate,City,State Abbrebiation,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,State Name
0,1,1/31/1992,Minneapolis,GA,55401,300,300,0,9/4/2020 0:15,2021-12-16 17:42:00,Georgia
1,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,2021-04-21 10:54:00,Alabama
2,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,2022-06-30 22:22:00,North Carolina
3,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,2020-12-30 10:57:00,North Carolina
4,6,10/9/1995,G,AL,85588,7085,7395,310,8/18/2020 14:28,2022-06-08 23:55:00,Alabama

In [28]:
#Move 'State Name' column to position after 'State Abbreviation' column, for this we use two methods together, pop() and insert()

# Step 1: Store the column data and remove it from its original position
state_name_col = reward_df_dropped.pop('State Name')

# Step 2: Insert the column back into the DataFrame at the new position
    # The first argument (3) specifies the new position for the column (zero-relative).
    # The second argument ('State Name') specifies the new inserted column name.
    # The third argument (col_a) is the data of the column.
reward_df_dropped.insert(4, "State Name", state_name_col)

reward_df_dropped.head(3)

,User ID,Birthdate,City,State Abbrebiation,State Name,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen
0,1,1/31/1992,Minneapolis,GA,Georgia,55401,300,300,0,9/4/2020 0:15,2021-12-16 17:42:00
1,3,1/11/1990,Merida,AL,Alabama,97204,330,330,0,10/13/2020 16:20,2021-04-21 10:54:00
2,4,4/16/1990,Winston-Salem,NC,North Carolina,27106,10790,14290,3500,8/18/2020 13:21,2022-06-30 22:22:00

In [29]:
# Get list of unique values from zip column
zip_unique_values = reward_df_dropped["Zip"].unique()

# sort the values
zip_unique_values = sorted(zip_unique_values)
zip_unique_values

['10538',
 '11768',
 '11787',
 '13026',
 '13078',
 '13492',
 '13753',
 '14530',
 '15217',
 '19352',
 '19355',
 '19382',
 '1945',
 '2030',
 '2067',
 '20814',
 '21093',
 '22213',
 '2332',
 '2478',
 '2493',
 '2532',
 '2653',
 '27012',
 '27013',
 '27051',
 '27101',
 '27103',
 '27104',
 '27106',
 '27107',
 '27109',
 '27127',
 '27360',
 '27406',
 '27410',
 '27516',
 '27707-1634',
 '28078',
 '28079',
 '28097',
 '28115',
 '28117',
 '28173',
 '28205',
 '28209',
 '28216',
 '28262',
 '28269',
 '28277',
 '28462',
 '28655',
 '29204',
 '29466',
 '30165',
 '30273',
 '30311',
 '30338',
 '32174',
 '32223',
 '32608',
 '33157',
 '33410',
 '33596',
 '33908',
 '37204',
 '37205',
 '38112',
 '40222',
 '45174',
 '45419',
 '53217',
 '55401',
 '55439',
 '60048',
 '60085',
 '60515',
 '6067',
 '6880',
 '69694',
 '7481',
 '75205',
 '75230',
 '78620',
 '7901',
 '80123',
 '8075',
 '85588',
 '88101',
 '90266',
 '92078',
 '93312',
 '969',
 '97204']

In [30]:
# Truncate all the zip codes more than 5 digits into 5 digits at max, we use string slicing
reward_df_dropped['Zip'] = reward_df_dropped['Zip'].str[:5]

In [31]:
# Learn Boolean indexing

Boolean indexing in pandas is a way to filter data in a DataFrame or Series using True/False conditions.

Instead of selecting rows by position or label, you create a condition (a boolean mask), and pandas returns only the rows where the condition is True.

In [33]:
# create a boolean index to check for zip codes with a length of five digits
# Assign true if length == 5, else false
zip_code_boolean_index = reward_df_dropped['Zip'].str.len() == 5

# display result of boolean index
zip_code_boolean_index

0       True
1       True
2       True
3       True
4       True
       ...
167     True
168     True
169     True
170     True
171    False
Name: Zip, Length: 172, dtype: bool

In [34]:
# Drop those zip codes not having length ewuals to 5
reward_df_dropped = reward_df_dropped[zip_code_boolean_index]

In [35]:
# Get list of unique values from zip column
zip_unique_values = reward_df_dropped["Zip"].unique()

# sort the values
zip_unique_values = sorted(zip_unique_values)
zip_unique_values

['10538',
 '11768',
 '11787',
 '13026',
 '13078',
 '13492',
 '13753',
 '14530',
 '15217',
 '19352',
 '19355',
 '19382',
 '20814',
 '21093',
 '22213',
 '27012',
 '27013',
 '27051',
 '27101',
 '27103',
 '27104',
 '27106',
 '27107',
 '27109',
 '27127',
 '27360',
 '27406',
 '27410',
 '27516',
 '27707',
 '28078',
 '28079',
 '28097',
 '28115',
 '28117',
 '28173',
 '28205',
 '28209',
 '28216',
 '28262',
 '28269',
 '28277',
 '28462',
 '28655',
 '29204',
 '29466',
 '30165',
 '30273',
 '30311',
 '30338',
 '32174',
 '32223',
 '32608',
 '33157',
 '33410',
 '33596',
 '33908',
 '37204',
 '37205',
 '38112',
 '40222',
 '45174',
 '45419',
 '53217',
 '55401',
 '55439',
 '60048',
 '60085',
 '60515',
 '69694',
 '75205',
 '75230',
 '78620',
 '80123',
 '85588',
 '88101',
 '90266',
 '92078',
 '93312',
 '97204']

In [36]:
len(reward_df_dropped)

155

In [38]:
# While iteratively checking the data, we find that there are some unwanted things in the data
# Like city name being Lmao, G
reward_df_dropped = reward_df_dropped[reward_df_dropped['City'] != 'G']

reward_df_dropped = reward_df_dropped[reward_df_dropped['City'] != 'Lmao']

In [39]:
len(reward_df_dropped)

153

In [40]:
reward_df_dropped

,User ID,Birthdate,City,State Abbrebiation,State Name,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen
0,1,1/31/1992,Minneapolis,GA,Georgia,55401,300,300,0,9/4/2020 0:15,2021-12-16 17:42:00
1,3,1/11/1990,Merida,AL,Alabama,97204,330,330,0,10/13/2020 16:20,2021-04-21 10:54:00
2,4,4/16/1990,Winston-Salem,NC,North Carolina,27106,10790,14290,3500,8/18/2020 13:21,2022-06-30 22:22:00
3,5,3/24/1994,Winston-Salem,NC,North Carolina,27109,650,650,0,8/21/2020 11:27,2020-12-30 10:57:00
5,10,7/20/1999,Winston Salem,NC,North Carolina,27106,8465,8515,50,8/22/2020 14:42,2022-04-09 14:10:00
...,...,...,...,...,...,...,...,...,...,...,...
166,7220,8/7/1999,Winston-Salem,NC,North Carolina,27106,430,430,0,6/22/2022 17:36,2022-06-26 16:39:00
167,7219,6/12/2004,Lutherville,MD,Maryland,21093,490,490,0,6/22/2022 17:28,2022-06-30 08:43:00
168,7220,8/7/1999,Winston-Salem,NC,North Carolina,27106,430,430,0,6/22/2022 17:36,2022-06-26 16:39:00
169,7227,3/14/2000,Clemmons,NC,North Carolina,27012,460,460,0,6/23/2022 22:18,2022-06-29 23:40:00
170,7230,5/18/1999,Winston Salem,NC,North Carolina,27107,410,410,0,6/24/2022 16:03,2022-06-24 16:06:00